### ISSUE TITLE
Should not crash when graphql returns an error

### ISSUE THREAD

**Issue by Vanuan** [datagovua/edrpou-static#2]
```
Listening on port 80
Error
    at new ApolloError (file:///src/jspm_packages/npm/apollo-client@0.4.12/errors.js:14:22)
    at file:///src/jspm_packages/npm/apollo-client@0.4.12/QueryManager.js:126:39
    at file:///src/jspm_packages/npm/apollo-client@0.4.12/QueryManager.js:547:17
    at file:///src/jspm_packages/npm/lodash._basefor@3.0.3/index.js:40:11
    at baseForOwn (file:///src/jspm_packages/npm/lodash.forown@4.2.0/index.js:22:20)
    at forOwn (file:///src/jspm_packages/npm/lodash.forown@4.2.0/index.js:54:20)
    at QueryManager.broadcastQueries (file:///src/jspm_packages/npm/apollo-client@0.4.12/QueryManager.js:544:9)
    at QueryManager.broadcastNewStore (file:///src/jspm_packages/npm/apollo-client@0.4.12/QueryManager.js:55:14)
    at file:///src/jspm_packages/npm/apollo-client@0.4.12/index.js:91:40
    at Object.dispatch (file:///src/jspm_packages/npm/redux@3.5.2/lib/applyMiddleware.js:45:18)
    at file:///src/jspm_packages/npm/apollo-client@0.4.12/QueryManager.js:423:29
    at lib$es6$promise$$internal$$tryCatch (file:///src/jspm_packages/npm/es6-promise@3.2.1/dist/es6-promise.js:362:16)
    at lib$es6$promise$$internal$$invokeCallback (file:///src/jspm_packages/npm/es6-promise@3.2.1/dist/es6-promise.js:374:17)
    at lib$es6$promise$$internal$$publish (file:///src/jspm_packages/npm/es6-promise@3.2.1/dist/es6-promise.js:345:11)
    at lib$es6$promise$asap$$flush (file:///src/jspm_packages/npm/es6-promise@3.2.1/dist/es6-promise.js:119:9)
    at nextTickCallbackWith0Args (node.js:436:9)
[ { message: 'request to http://edr-api/api/companies?where={"edrpou":"00308376"} failed, reason: connect ECONNREFUSED 10.0.0.2:80',
    locations: [ [Object] ] } ]
Error
    at new ApolloError (file:///src/jspm_packages/npm/apollo-client@0.4.12/errors.js:14:22)
    at file:///src/jspm_packages/npm/apollo-client@0.4.12/QueryManager.js:126:39
    at file:///src/jspm_packages/npm/apollo-client@0.4.12/QueryManager.js:547:17
    at file:///src/jspm_packages/npm/lodash._basefor@3.0.3/index.js:40:11
    at baseForOwn (file:///src/jspm_packages/npm/lodash.forown@4.2.0/index.js:22:20)
    at forOwn (file:///src/jspm_packages/npm/lodash.forown@4.2.0/index.js:54:20)
    at QueryManager.broadcastQueries (file:///src/jspm_packages/npm/apollo-client@0.4.12/QueryManager.js:544:9)
    at QueryManager.broadcastNewStore (file:///src/jspm_packages/npm/apollo-client@0.4.12/QueryManager.js:55:14)
    at file:///src/jspm_packages/npm/apollo-client@0.4.12/index.js:91:40
    at Object.dispatch (file:///src/jspm_packages/npm/redux@3.5.2/lib/applyMiddleware.js:45:18)
    at file:///src/jspm_packages/npm/apollo-client@0.4.12/QueryManager.js:423:29
    at lib$es6$promise$$internal$$tryCatch (file:///src/jspm_packages/npm/es6-promise@3.2.1/dist/es6-promise.js:362:16)
    at lib$es6$promise$$internal$$invokeCallback (file:///src/jspm_packages/npm/es6-promise@3.2.1/dist/es6-promise.js:374:17)
    at lib$es6$promise$$internal$$publish (file:///src/jspm_packages/npm/es6-promise@3.2.1/dist/es6-promise.js:345:11)
    at lib$es6$promise$asap$$flush (file:///src/jspm_packages/npm/es6-promise@3.2.1/dist/es6-promise.js:119:9)
    at nextTickCallbackWith0Args (node.js:436:9)
[ { message: 'request to http://edr-api/api/companies?where={"edrpou":"00380936"} failed, reason: connect ECONNREFUSED 10.0.0.2:80',
    locations: [ [Object] ] } ]

```

**Comment by Vanuan** [comment]
There should be a nice error page.
